name: azure-run-loadtest
on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes (minute hour month_day month week_day)
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Load Test Resource Group'
        required: true
        default: 'rg-loadtest01'
      name:
        description: 'Load Test Resource Name'
        required: true
        default: 'loadtest01'
      host:
        description: 'Host'
        required: true
        default: 'avloadtestaks.eastus.cloudapp.azure.com'
      number_of_users:
        description: 'Number of users'
        required: true
        default: '1'
      duration:
        description: 'Duration in seconds'
        required: true
        default: '120'
jobs:
  run-loadtest:
    runs-on: ubuntu-latest
    env:
      RG: "${{ github.event.inputs.resource_group || 'rg-loadtest01' }}"
      NAME: "${{ github.event.inputs.name || 'loadtest01' }}"
      HOST: "${{ github.event.inputs.host || 'avloadtestaks.eastus.cloudapp.azure.com' }}"
      NUMBER_OF_USERS: "${{ github.event.inputs.number_of_users || '1' }}"
      DURATION: "${{ github.event.inputs.duration || '120' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run netty_hello_test
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'loadtestservice/netty_hello_test.yml'
          resourceGroup: ${{ env.RG }}
          loadTestResource: ${{ env.NAME }}
          env: |
            [
              {
                "name": "number_of_users",
                "value": "${{ env.NUMBER_OF_USERS }}"
              },
              {
                "name": "ramp_period_seconds",
                "value": "10"
              },
              {
                "name": "duration_seconds",
                "value": "${{ env.DURATION }}"
              },
              {
                "name": "protocol",
                "value": "http"
              },
              {
                "name": "host",
                "value": "${{ env.HOST }}"
              },
              {
                "name": "port",
                "value": "80"
              },
              {
                "name": "path",
                "value": "/"
              }
            ]

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest

      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear